### ISSUE TITLE
Only showing servers IP rather than the one defined in the servers display IP

### ISSUE THREAD

**Issue by dragonmunday12** [OpenGamePanel/Module-DSi#7]
This issue I found when first trying DSI
Shows internal IP rather than display IP defined when linking to a server agent.
![broken](https://user-images.githubusercontent.com/5354668/28157151-68745068-676a-11e7-8ee6-ba3f249d66af.png)

**Comment by own3mall** [comment]
Is it fixed now?  Please close the issue if it is.

**Comment by own3mall** [comment]
I believe this was fixed by @oNdsen via a base change.  But I fixed some other issues.
